meta_product_name: "FestivOut"
meta_title: "FestivOut - Focus on the moment enjoy the music."
meta_description: "FestivOut is an app that makes your experience in festivals smoother, it helps you get what you want to do and where you want to go faster."
meta_image: "cover.png"